### ISSUE TITLE
Erro - Unable to locate message source for category 'infoweb/analytics'.

### ISSUE THREAD

**Issue by wilsonfalai** [infoweb-internet-solutions/yii2-cms-analytics#10]
the documentation says:
Import the translations and use category 'infoweb/analytics':

yii i18n/import @infoweb/analytics/messages

I dont understand. Can you help-me

**Comment by infoweb-internet-solutions** [comment]
You can just ignore this, that's for our cms system and it's only translated to dutch  
Default language is English  
Or you can read this:  
http://stuff.cebe.cc/yii2docs/guide-tutorial-i18n.html  
and use http://stuff.cebe.cc/yii2docs/yii-i18n-dbmessagesource.html  
  
And use this extension to manage your translations:  
https://github.com/zelenin/yii2-i18n-module

**Comment by wilsonfalai** [comment]
Thanks!
