### ISSUE TITLE
How to show Chart Pageviews?

### ISSUE THREAD

**Issue by adethis** [infoweb-internet-solutions/yii2-cms-analytics#14]
How to show Chart Pageviews? like a Sessions Chart

**Comment by infoweb-internet-solutions** [comment]
if you follow the instructions you can already see a chart with sessions?
you can just fork this and edit yourself
all the info you need:
[Google Analytics Query Explorer 2](https://ga-dev-tools.appspot.com/explorer/)
[Google API Php Client](https://github.com/google/google-api-php-client)
[Developer Documentation](https://developers.google.com/api-client-library/php)
[Google Charts](https://developers.google.com/chart/?hl=nl)

**Comment by adethis** [comment]
ok thanks for reply and that guide/info.
